In [1]:
import numpy as np
class LinearModel:
    def __init__(self,*args):
        self.x = None
        self.y = None
        
    def train(self,x,y):
        self.x = np.array(x)
        self.y = np.array(y)
        self.n  = len(self.x)
        self.x_sum = (self.x).sum()
        self.y_sum = (self.y).sum()
        self.sum_xy = (self.x *self.y).sum()
        self.x_squared_sum = (self.x**2).sum()
        self.num = self.n *self.sum_xy - self.x_sum*self.y_sum
        self.den = self.n * self.x_squared_sum - (self.x_sum)**2
        
        self.b_ = self.num / self.den
        self.a_ = self.y_sum/self.n - self.b_ * (self.x).mean()
        return (self.a_,self.b_)
    # y = a+bx
        
        
    def predict (self,x):
        return self.a_ +self.b_ *np.array(x)
    
    def loss(self,x,y):
       
        self.ly = np.array(y)
        self.p_y =np.array(self.predict(x))
        return ((self.p_y - self.ly)**2).mean()
        
        
    def __str__(self):
        return "a simple linear regression model"
        
        

In [48]:
model1.loss(x,y)

0.28503142774510715

In [44]:
model1 = LinearModel()

In [ ]:
model1 

In [19]:
print(model1)


a simple linear regression model


In [47]:
model1.predict(2.7)

6.541352549889133

In [38]:
data = np.array([[4.2,8.4],[2.7,6.2],[8.9,12.5],[8.2,10.5],[10.2,13]])


In [21]:
data.ndim


2

In [22]:
data.shape


(5, 2)

In [23]:
data.dtype


dtype('float64')

In [24]:
data.size


10

In [25]:
data

array([[ 4.2,  8.4],
       [ 2.7,  6.2],
       [ 8.9, 12.5],
       [ 8.2, 10.5],
       [10.2, 13. ]])

In [26]:
x=data[:,0]

In [27]:
x

array([ 4.2,  2.7,  8.9,  8.2, 10.2])

In [28]:
y= data[:,1]

In [46]:
model1.train(x,y)

(4.207452038947264, 0.8644075966451369)

In [32]:
model1.predict(12.5)

15.012546997011476

In [6]:
z=[2,3,4]
len(z)

3

In [50]:
y


array([ 8.4,  6.2, 12.5, 10.5, 13. ])